# Generated by Django 5.0.1 on 2026-03-24 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoveRows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_love', models.CharField(max_length=255)),
                ('level_of_love', models.CharField(max_length=255)),
                ('loves_reward', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VIPLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='The VIP level (e.g., 1, 2, 3, etc.)', unique=True)),
                ('recharge_amount', models.FloatField(help_text='The amount required to recharge to reach this VIP level')),
                ('claim_amount', models.FloatField(help_text='The amount available to claim for this VIP level')),
            ],
            options={
                'verbose_name': 'VIP Level',
                'verbose_name_plural': 'VIP Levels',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='UserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linked_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_claimed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vip_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_hall.viplevel')),
            ],
            options={
                'unique_together': {('user', 'vip_level')},
            },
        ),
    ]
