# Generated by Django 5.0.1 on 2026-03-24 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanableCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='loanable_coins/')),
                ('network', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('nrc_front_pic', models.ImageField(upload_to='loan_nrc/')),
                ('nrc_back_pic', models.ImageField(upload_to='loan_nrc/')),
                ('loan_terms', models.IntegerField(help_text='Loan duration in days')),
                ('total_interest', models.FloatField()),
                ('repayment_amount', models.FloatField()),
                ('account_type', models.CharField(choices=[('Spot', 'Spot'), ('Normal', 'Normal'), ('Trading', 'Trading')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loanablecoin')),
            ],
        ),
    ]
