# Generated by Django 5.0.1 on 2026-03-24 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(help_text='Duration of the trade (timedelta object)')),
                ('win_percentage', models.FloatField(help_text='Win percentage for this duration (e.g., 10.0 for 10%)')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=1024)),
                ('trade_method', models.CharField(choices=[('Buy Up', 'Buy Up'), ('Buy Down', 'Buy Down')], max_length=20)),
                ('amount', models.FloatField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('open_price', models.FloatField(null=True)),
                ('close_price', models.FloatField(null=True)),
                ('profit_or_loss', models.FloatField(blank=True, help_text='Profit or loss amount (set when trade is created)', null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='True if the trade is closed')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.duration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
